### ISSUE TITLE
Allow admin users to edit `sites`, `districts`, `regions` and `zones` and add new `sites`

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/mnutrition-milestones#3]
- [x] Backend part https://github.com/eHealthAfrica/mnutrition-entities/issues/5
- [x] UI part https://github.com/eHealthAfrica/mnutrition-app/issues/174
  Remaining issues:
- [ ] Dashes instead of camel case:
  - [ ] in the app https://github.com/eHealthAfrica/mnutrition-app/issues/213
  - [ ] bootstrap and the db https://github.com/eHealthAfrica/mnutrition-bootstrap/issues/32
- [ ] Typo (app, bootstrap & db): https://github.com/eHealthAfrica/mnutrition-bootstrap/issues/29
